from app.models.models import Disease, db

DISEASE_DATA = [
    # ---------- Apple ----------
    {
        "name": "Apple___Apple_scab",
        "crop_type": "Apple",
        "symptoms": "Olive-green to black scabby lesions on leaves and fruit; deformed fruit; early leaf drop",
        "causes": "Venturia inaequalis fungus; cool wet spring conditions",
        "organic_treatment": "Lime sulfur spray; copper fungicides; remove fallen leaves; proper pruning",
        "chemical_treatment": "Captan 50 WP at 2.5 g/L; Myclobutanil; Difenoconazole",
        "preventive_measures": "Resistant cultivars; sanitation of fallen leaves; proper tree spacing",
    },
    {
        "name": "Apple___Black_rot",
        "crop_type": "Apple",
        "symptoms": "Circular lesions with purple borders on leaves; rotting fruit with concentric rings",
        "causes": "Botryosphaeria obtusa fungus; wounds and stressed trees",
        "organic_treatment": "Prune dead wood; copper-based sprays; remove mummified fruit",
        "chemical_treatment": "Captan; Thiophanate-methyl; Myclobutanil",
        "preventive_measures": "Remove dead wood; proper pruning; orchard sanitation",
    },
    {
        "name": "Apple___Cedar_apple_rust",
        "crop_type": "Apple",
        "symptoms": "Bright orange-yellow spots on upper leaf surfaces; tube-like structures beneath leaves",
        "causes": "Gymnosporangium juniperi-virginianae; requires juniper alternate host",
        "organic_treatment": "Remove nearby juniper hosts; sulfur-based sprays",
        "chemical_treatment": "Myclobutanil; Propiconazole; Mancozeb",
        "preventive_measures": "Plant resistant varieties; remove juniper hosts within 1 mile",
    },
    {
        "name": "Apple___healthy",
        "crop_type": "Apple",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Maintain regular organic fertilization; compost application",
        "chemical_treatment": "Preventive fungicide if risk is high",
        "preventive_measures": "Regular monitoring; balanced nutrition; proper irrigation",
    },
    # ---------- Blueberry ----------
    {
        "name": "Blueberry___healthy",
        "crop_type": "Blueberry",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Organic mulch; balanced compost",
        "chemical_treatment": "Preventive fungicide if risk is high",
        "preventive_measures": "Maintain soil pH 4.5-5.5; regular monitoring",
    },
    # ---------- Cherry ----------
    {
        "name": "Cherry_(including_sour)___Powdery_mildew",
        "crop_type": "Cherry",
        "symptoms": "White powdery coating on leaves and shoots; distorted young leaves",
        "causes": "Podosphaera clandestina fungus; warm dry days with cool nights",
        "organic_treatment": "Potassium bicarbonate spray; neem oil; sulfur dust",
        "chemical_treatment": "Myclobutanil; Trifloxystrobin; Propiconazole",
        "preventive_measures": "Prune for airflow; avoid excess nitrogen; plant resistant varieties",
    },
    {
        "name": "Cherry_(including_sour)___healthy",
        "crop_type": "Cherry",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Compost application; foliar micronutrients",
        "chemical_treatment": "Preventive copper spray in spring",
        "preventive_measures": "Regular monitoring; good canopy airflow",
    },
    # ---------- Corn ----------
    {
        "name": "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot",
        "crop_type": "Corn",
        "symptoms": "Rectangular gray-tan lesions between leaf veins; premature leaf death",
        "causes": "Cercospora zeae-maydis; warm humid conditions; crop debris",
        "organic_treatment": "Crop rotation; remove crop residue; improve air circulation",
        "chemical_treatment": "Azoxystrobin; Pyraclostrobin; Propiconazole",
        "preventive_measures": "Resistant hybrids; crop rotation; reduce surface residue",
    },
    {
        "name": "Corn_(maize)___Common_rust_",
        "crop_type": "Corn",
        "symptoms": "Small cinnamon-brown pustules on both leaf surfaces; heavy infection causes yellowing",
        "causes": "Puccinia sorghi; cool temperatures 60-77°F with high humidity",
        "organic_treatment": "Remove infected leaves; improve air circulation",
        "chemical_treatment": "Mancozeb; Propiconazole; Azoxystrobin + Propiconazole",
        "preventive_measures": "Plant resistant hybrids; early planting; monitor regularly",
    },
    {
        "name": "Corn_(maize)___Northern_Leaf_Blight",
        "crop_type": "Corn",
        "symptoms": "Long cigar-shaped grayish-green lesions; lesions turn tan with age",
        "causes": "Exserohilum turcicum; moderate temperatures with high humidity",
        "organic_treatment": "Remove crop debris; improve air circulation; Trichoderma bio-fungicides",
        "chemical_treatment": "Propiconazole; Azoxystrobin + Propiconazole; Tebuconazole",
        "preventive_measures": "Resistant hybrids; crop rotation; avoid dense planting",
    },
    {
        "name": "Corn_(maize)___healthy",
        "crop_type": "Corn",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Balanced compost; crop rotation",
        "chemical_treatment": "Preventive fungicide if disease pressure is high",
        "preventive_measures": "Proper spacing; balanced fertilization; scout regularly",
    },
    # ---------- Grape ----------
    {
        "name": "Grape___Black_rot",
        "crop_type": "Grape",
        "symptoms": "Brown circular lesions on leaves; mummified berries; black pycnidia on lesions",
        "causes": "Guignardia bidwellii; warm wet weather during bloom",
        "organic_treatment": "Copper-based sprays; remove mummified berries; improve canopy airflow",
        "chemical_treatment": "Mancozeb 75 WP; Captan; Myclobutanil (Rally)",
        "preventive_measures": "Remove mummified fruit; proper canopy management; timely dormant sprays",
    },
    {
        "name": "Grape___Esca_(Black_Measles)",
        "crop_type": "Grape",
        "symptoms": "Tiger-stripe leaf pattern; dark brown wood streaking; berry spotting",
        "causes": "Complex of wood-decay fungi (Phaeomoniella, Phaeoacremonium)",
        "organic_treatment": "Prune infected wood; wound sealants; improve vine vigor",
        "chemical_treatment": "No curative chemical; preventive sodium arsenite (where legal)",
        "preventive_measures": "Avoid large pruning wounds; apply wound protectants; remove infected vines",
    },
    {
        "name": "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)",
        "crop_type": "Grape",
        "symptoms": "Dark brown irregular spots near leaf margins; premature defoliation",
        "causes": "Pseudocercospora vitis; warm humid conditions",
        "organic_treatment": "Copper hydroxide spray; remove fallen leaves",
        "chemical_treatment": "Mancozeb; Captan; Tebuconazole",
        "preventive_measures": "Canopy management; avoid overhead irrigation; remove leaf litter",
    },
    {
        "name": "Grape___healthy",
        "crop_type": "Grape",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Compost; balanced nutrition",
        "chemical_treatment": "Preventive copper/sulfur sprays",
        "preventive_measures": "Proper canopy management; regular scouting",
    },
    # ---------- Orange ----------
    {
        "name": "Orange___Haunglongbing_(Citrus_greening)",
        "crop_type": "Citrus",
        "symptoms": "Blotchy leaf mottling; small lopsided fruit; bitter taste; twig dieback",
        "causes": "Candidatus Liberibacter asiaticus; spread by Asian citrus psyllid",
        "organic_treatment": "No cure; manage psyllid with insecticidal soaps; remove infected trees",
        "chemical_treatment": "Control psyllid with Imidacloprid; Dimethoate; Thiamethoxam",
        "preventive_measures": "Disease-free planting material; psyllid monitoring; quarantine infected trees",
    },
    # ---------- Peach ----------
    {
        "name": "Peach___Bacterial_spot",
        "crop_type": "Peach",
        "symptoms": "Water-soaked spots on leaves turning angular brown; shot-hole appearance; fruit lesions",
        "causes": "Xanthomonas arboricola pv. pruni; warm wet weather",
        "organic_treatment": "Copper-based bactericides; remove infected tissue",
        "chemical_treatment": "Oxytetracycline; copper hydroxide; fixed copper",
        "preventive_measures": "Resistant varieties; avoid overhead irrigation; prune for airflow",
    },
    {
        "name": "Peach___healthy",
        "crop_type": "Peach",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Balanced organic fertilizer; compost",
        "chemical_treatment": "Preventive dormant copper spray",
        "preventive_measures": "Regular scouting; proper pruning",
    },
    # ---------- Pepper ----------
    {
        "name": "Pepper,_bell___Bacterial_spot",
        "crop_type": "Pepper",
        "symptoms": "Water-soaked spots on leaves becoming brown with yellow halo; fruit lesions",
        "causes": "Xanthomonas campestris pv. vesicatoria; warm wet weather",
        "organic_treatment": "Copper-based sprays; remove infected debris",
        "chemical_treatment": "Copper hydroxide + Mancozeb; Oxytetracycline",
        "preventive_measures": "Use disease-free seed; crop rotation; avoid overhead irrigation",
    },
    {
        "name": "Pepper,_bell___healthy",
        "crop_type": "Pepper",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Compost; balanced fertilization",
        "chemical_treatment": "Preventive copper spray if risk is high",
        "preventive_measures": "Proper spacing; regular monitoring",
    },
    # ---------- Potato ----------
    {
        "name": "Potato___Early_blight",
        "crop_type": "Potato",
        "symptoms": "Dark brown concentric ring lesions on older leaves; yellowing; defoliation",
        "causes": "Alternaria solani; warm humid conditions; plant stress",
        "organic_treatment": "Neem oil; baking soda spray; remove infected leaves",
        "chemical_treatment": "Mancozeb 75 WP at 2 g/L; Chlorothalonil; Azoxystrobin",
        "preventive_measures": "Crop rotation; remove plant debris; balanced fertilization",
    },
    {
        "name": "Potato___Late_blight",
        "crop_type": "Potato",
        "symptoms": "Water-soaked lesions on leaves; white sporulation on undersides; tuber rot",
        "causes": "Phytophthora infestans; cool wet weather; infected seed tubers",
        "organic_treatment": "Copper hydroxide spray; remove infected plants; improve drainage",
        "chemical_treatment": "Cymoxanil + Mancozeb; Propamocarb; Metalaxyl-M + Mancozeb",
        "preventive_measures": "Certified disease-free seed; hilling; proper field drainage",
    },
    {
        "name": "Potato___healthy",
        "crop_type": "Potato",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Balanced compost; hilling",
        "chemical_treatment": "Preventive fungicide if blight risk is high",
        "preventive_measures": "Crop rotation; certified seed; regular scouting",
    },
    # ---------- Raspberry ----------
    {
        "name": "Raspberry___healthy",
        "crop_type": "Raspberry",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Organic mulch; compost",
        "chemical_treatment": "Preventive copper spray",
        "preventive_measures": "Prune old canes; maintain good airflow",
    },
    # ---------- Soybean ----------
    {
        "name": "Soybean___healthy",
        "crop_type": "Soybean",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Balanced organic fertilizer",
        "chemical_treatment": "Preventive fungicide if disease pressure is high",
        "preventive_measures": "Crop rotation; proper plant spacing; regular scouting",
    },
    # ---------- Squash ----------
    {
        "name": "Squash___Powdery_mildew",
        "crop_type": "Squash",
        "symptoms": "White powdery spots on leaves and stems; leaves yellow and die prematurely",
        "causes": "Podosphaera xanthii / Erysiphe cichoracearum; warm dry weather",
        "organic_treatment": "Potassium bicarbonate; neem oil; milk spray (1:9 dilution)",
        "chemical_treatment": "Myclobutanil; Triadimefon; Azoxystrobin",
        "preventive_measures": "Resistant varieties; proper spacing; avoid wetting foliage",
    },
    # ---------- Strawberry ----------
    {
        "name": "Strawberry___Leaf_scorch",
        "crop_type": "Strawberry",
        "symptoms": "Small dark purple spots on leaves expanding to scorched appearance; leaf death",
        "causes": "Diplocarpon earlianum fungus; warm humid conditions",
        "organic_treatment": "Remove infected leaves; copper-based spray; improve drainage",
        "chemical_treatment": "Captan; Myclobutanil; Pyraclostrobin",
        "preventive_measures": "Remove old foliage; avoid overhead irrigation; resistant varieties",
    },
    {
        "name": "Strawberry___healthy",
        "crop_type": "Strawberry",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Organic mulch; compost tea",
        "chemical_treatment": "Preventive fungicide at fruit set",
        "preventive_measures": "Remove runners; regular scouting; drip irrigation",
    },
    # ---------- Tomato ----------
    {
        "name": "Tomato___Bacterial_spot",
        "crop_type": "Tomato",
        "symptoms": "Small water-soaked leaf spots turning brown with yellow halo; fruit spots",
        "causes": "Xanthomonas species; warm wet weather; splashing water",
        "organic_treatment": "Copper-based bactericides; remove infected debris",
        "chemical_treatment": "Copper hydroxide + Mancozeb; Oxytetracycline",
        "preventive_measures": "Disease-free seed; crop rotation; drip irrigation",
    },
    {
        "name": "Tomato___Early_blight",
        "crop_type": "Tomato",
        "symptoms": "Concentric ring patterns on older leaves; yellowing around lesions; stem cankers",
        "causes": "Alternaria solani; warm humid conditions; plant stress",
        "organic_treatment": "Neem oil; baking soda spray; remove infected leaves",
        "chemical_treatment": "Mancozeb 75 WP at 2 g/L; Chlorothalonil; Azoxystrobin",
        "preventive_measures": "Remove plant debris; mulching; balanced fertilization",
    },
    {
        "name": "Tomato___Late_blight",
        "crop_type": "Tomato",
        "symptoms": "Dark brown spots on leaves and stems; white mold on underside; fruit rot",
        "causes": "Phytophthora infestans; high humidity and cool temperatures",
        "organic_treatment": "Copper-based fungicides; neem oil; remove affected leaves",
        "chemical_treatment": "Mancozeb 75 WP at 2.5 g/L; Metalaxyl + Mancozeb; Chlorothalonil",
        "preventive_measures": "Resistant varieties; avoid overhead irrigation; crop rotation",
    },
    {
        "name": "Tomato___Leaf_Mold",
        "crop_type": "Tomato",
        "symptoms": "Pale green-yellow spots on upper leaf surface; olive-brown mold on underside",
        "causes": "Passalora fulva; high humidity above 85%; poor ventilation",
        "organic_treatment": "Improve ventilation; reduce humidity; remove infected leaves",
        "chemical_treatment": "Chlorothalonil; Mancozeb; Difenoconazole",
        "preventive_measures": "Resistant varieties; proper spacing; good greenhouse ventilation",
    },
    {
        "name": "Tomato___Septoria_leaf_spot",
        "crop_type": "Tomato",
        "symptoms": "Numerous small circular spots with dark borders and light centers on lower leaves",
        "causes": "Septoria lycopersici; warm wet conditions; infected debris",
        "organic_treatment": "Remove infected leaves; copper fungicides; improve air circulation",
        "chemical_treatment": "Mancozeb; Chlorothalonil; Azoxystrobin",
        "preventive_measures": "Crop rotation; mulch to prevent soil splash; remove debris",
    },
    {
        "name": "Tomato___Spider_mites Two-spotted_spider_mite",
        "crop_type": "Tomato",
        "symptoms": "Fine stippling on leaves; bronzing; fine webbing on underside; leaf drop",
        "causes": "Tetranychus urticae mite; hot dry conditions; dusty environments",
        "organic_treatment": "Neem oil; insecticidal soap; predatory mites (Phytoseiulus persimilis)",
        "chemical_treatment": "Abamectin; Bifenazate; Spiromesifen miticides",
        "preventive_measures": "Maintain plant moisture; avoid dusty conditions; avoid pyrethroid overuse",
    },
    {
        "name": "Tomato___Target_Spot",
        "crop_type": "Tomato",
        "symptoms": "Brown circular lesions with concentric rings; yellow halo; defoliation",
        "causes": "Corynespora cassiicola; warm humid conditions",
        "organic_treatment": "Remove infected leaves; copper-based sprays",
        "chemical_treatment": "Azoxystrobin; Difenoconazole; Fluxapyroxad",
        "preventive_measures": "Crop rotation; remove debris; avoid leaf wetness",
    },
    {
        "name": "Tomato___Tomato_Yellow_Leaf_Curl_Virus",
        "crop_type": "Tomato",
        "symptoms": "Upward leaf curling; yellowing leaf margins; stunted growth; reduced fruit set",
        "causes": "Tomato yellow leaf curl virus (TYLCV); transmitted by whitefly",
        "organic_treatment": "Control whitefly with yellow sticky traps; reflective mulches; neem oil",
        "chemical_treatment": "Control whitefly: Imidacloprid; Thiamethoxam; Spirotetramat",
        "preventive_measures": "Resistant varieties; whitefly monitoring; remove infected plants promptly",
    },
    {
        "name": "Tomato___Tomato_mosaic_virus",
        "crop_type": "Tomato",
        "symptoms": "Mosaic mottling on leaves; leaf distortion; stunted plants; reduced yield",
        "causes": "Tomato mosaic virus (ToMV); mechanical transmission; infected seed",
        "organic_treatment": "No cure; remove infected plants; sanitize tools",
        "chemical_treatment": "No direct chemical; control aphid vectors with insecticides",
        "preventive_measures": "Use certified virus-free seed; sanitize tools; wash hands; resistant varieties",
    },
    {
        "name": "Tomato___healthy",
        "crop_type": "Tomato",
        "symptoms": "No disease symptoms detected",
        "causes": "N/A",
        "organic_treatment": "Balanced compost; foliar micronutrients",
        "chemical_treatment": "Preventive copper spray if conditions are wet",
        "preventive_measures": "Regular monitoring; proper irrigation; crop rotation",
    },
]


def seed_diseases():
    if Disease.query.count() == 0:
        for d in DISEASE_DATA:
            db.session.add(Disease(**d))
        db.session.commit()
        print(f"Seeded {len(DISEASE_DATA)} diseases.")
